default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "careermap_poc_development") %>

test:
  <<: *default
  database: careermap_poc_test
  username: root
  password: password

production:
  <<: *default
  database: backend_production
  username: backend
  password: <%= ENV['BACKEND_DATABASE_PASSWORD'] %>
